 # the complier:
CC = gcc

# checking for warnings
CFLAGS = -Wall

# the executable
all: main

# creating the executable file
main: linked_list.o use_linked_list.o 
	$(CC) $(CFLAGS) -o main linked_list.o use_linked_list.o 

# creating object the first file
linked_list.o: linked_list.c linked_list.h
	$(CC) $(CFLAGS) -c linked_list.c

# creating object the second file 
use_linked_list.o: use_linked_list.c linked_list.h
	$(CC) $(CFLAGS) -c use_linked_list.c 

# delete the executable then the obejct file
clean: 
	rm -f main use_linked_list.o linked_list.o
